/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as KnowledgebaseRouteImport } from './routes/knowledgebase'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminKnowledgebaseRouteImport } from './routes/admin.knowledgebase'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminTicketsRouteImport } from './routes/admin.tickets'
import { Route as TicketsTicketIdRouteImport } from './routes/tickets.$ticketId'
import { Route as TicketsNewRouteImport } from './routes/tickets.new'
import { Route as AdminKnowledgebaseEditRouteImport } from './routes/admin.knowledgebase.edit'
import { Route as AdminKnowledgebaseNewRouteImport } from './routes/admin.knowledgebase.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgebaseRoute = KnowledgebaseRouteImport.update({
  id: '/knowledgebase',
  path: '/knowledgebase',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKnowledgebaseRoute = AdminKnowledgebaseRouteImport.update({
  id: '/knowledgebase',
  path: '/knowledgebase',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const TicketsTicketIdRoute = TicketsTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => TicketsRoute,
} as any)
const TicketsNewRoute = TicketsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TicketsRoute,
} as any)
const AdminKnowledgebaseEditRoute = AdminKnowledgebaseEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminKnowledgebaseRoute,
} as any)
const AdminKnowledgebaseNewRoute = AdminKnowledgebaseNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminKnowledgebaseRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/admin': typeof AdminRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/knowledgebase': typeof KnowledgebaseRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/verify': typeof VerifyRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/knowledgebase': typeof AdminKnowledgebaseRouteWithChildren
  '/admin/media': typeof AdminMediaRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/tickets/new': typeof TicketsNewRoute
  '/admin/knowledgebase/edit': typeof AdminKnowledgebaseEditRoute
  '/admin/knowledgebase/new': typeof AdminKnowledgebaseNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/admin': typeof AdminRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/knowledgebase': typeof KnowledgebaseRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/verify': typeof VerifyRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/knowledgebase': typeof AdminKnowledgebaseRouteWithChildren
  '/admin/media': typeof AdminMediaRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/tickets/new': typeof TicketsNewRoute
  '/admin/knowledgebase/edit': typeof AdminKnowledgebaseEditRoute
  '/admin/knowledgebase/new': typeof AdminKnowledgebaseNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/admin': typeof AdminRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/knowledgebase': typeof KnowledgebaseRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/verify': typeof VerifyRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/knowledgebase': typeof AdminKnowledgebaseRouteWithChildren
  '/admin/media': typeof AdminMediaRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/tickets/new': typeof TicketsNewRoute
  '/admin/knowledgebase/edit': typeof AdminKnowledgebaseEditRoute
  '/admin/knowledgebase/new': typeof AdminKnowledgebaseNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/admin'
    | '/change-password'
    | '/knowledgebase'
    | '/login'
    | '/profile'
    | '/tickets'
    | '/verify'
    | '/admin/audit-logs'
    | '/admin/categories'
    | '/admin/knowledgebase'
    | '/admin/media'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/tickets'
    | '/tickets/$ticketId'
    | '/tickets/new'
    | '/admin/knowledgebase/edit'
    | '/admin/knowledgebase/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/admin'
    | '/change-password'
    | '/knowledgebase'
    | '/login'
    | '/profile'
    | '/tickets'
    | '/verify'
    | '/admin/audit-logs'
    | '/admin/categories'
    | '/admin/knowledgebase'
    | '/admin/media'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/tickets'
    | '/tickets/$ticketId'
    | '/tickets/new'
    | '/admin/knowledgebase/edit'
    | '/admin/knowledgebase/new'
  id:
    | '__root__'
    | '/'
    | '/accept-invitation'
    | '/admin'
    | '/change-password'
    | '/knowledgebase'
    | '/login'
    | '/profile'
    | '/tickets'
    | '/verify'
    | '/admin/audit-logs'
    | '/admin/categories'
    | '/admin/knowledgebase'
    | '/admin/media'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/tickets'
    | '/tickets/$ticketId'
    | '/tickets/new'
    | '/admin/knowledgebase/edit'
    | '/admin/knowledgebase/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  KnowledgebaseRoute: typeof KnowledgebaseRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  TicketsRoute: typeof TicketsRouteWithChildren
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledgebase': {
      id: '/knowledgebase'
      path: '/knowledgebase'
      fullPath: '/knowledgebase'
      preLoaderRoute: typeof KnowledgebaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/knowledgebase': {
      id: '/admin/knowledgebase'
      path: '/knowledgebase'
      fullPath: '/admin/knowledgebase'
      preLoaderRoute: typeof AdminKnowledgebaseRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tickets/$ticketId': {
      id: '/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof TicketsTicketIdRouteImport
      parentRoute: typeof TicketsRoute
    }
    '/tickets/new': {
      id: '/tickets/new'
      path: '/new'
      fullPath: '/tickets/new'
      preLoaderRoute: typeof TicketsNewRouteImport
      parentRoute: typeof TicketsRoute
    }
    '/admin/knowledgebase/edit': {
      id: '/admin/knowledgebase/edit'
      path: '/edit'
      fullPath: '/admin/knowledgebase/edit'
      preLoaderRoute: typeof AdminKnowledgebaseEditRouteImport
      parentRoute: typeof AdminKnowledgebaseRoute
    }
    '/admin/knowledgebase/new': {
      id: '/admin/knowledgebase/new'
      path: '/new'
      fullPath: '/admin/knowledgebase/new'
      preLoaderRoute: typeof AdminKnowledgebaseNewRouteImport
      parentRoute: typeof AdminKnowledgebaseRoute
    }
  }
}

interface AdminKnowledgebaseRouteChildren {
  AdminKnowledgebaseEditRoute: typeof AdminKnowledgebaseEditRoute
  AdminKnowledgebaseNewRoute: typeof AdminKnowledgebaseNewRoute
}

const AdminKnowledgebaseRouteChildren: AdminKnowledgebaseRouteChildren = {
  AdminKnowledgebaseEditRoute: AdminKnowledgebaseEditRoute,
  AdminKnowledgebaseNewRoute: AdminKnowledgebaseNewRoute,
}

const AdminKnowledgebaseRouteWithChildren =
  AdminKnowledgebaseRoute._addFileChildren(AdminKnowledgebaseRouteChildren)

interface AdminRouteChildren {
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminKnowledgebaseRoute: typeof AdminKnowledgebaseRouteWithChildren
  AdminMediaRoute: typeof AdminMediaRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminKnowledgebaseRoute: AdminKnowledgebaseRouteWithChildren,
  AdminMediaRoute: AdminMediaRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminTicketsRoute: AdminTicketsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TicketsRouteChildren {
  TicketsTicketIdRoute: typeof TicketsTicketIdRoute
  TicketsNewRoute: typeof TicketsNewRoute
}

const TicketsRouteChildren: TicketsRouteChildren = {
  TicketsTicketIdRoute: TicketsTicketIdRoute,
  TicketsNewRoute: TicketsNewRoute,
}

const TicketsRouteWithChildren =
  TicketsRoute._addFileChildren(TicketsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInvitationRoute: AcceptInvitationRoute,
  AdminRoute: AdminRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  KnowledgebaseRoute: KnowledgebaseRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  TicketsRoute: TicketsRouteWithChildren,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
